'use strict';

/**
 * IMAGE ANALYSIS - PROMPTS
 * Centralized GPT prompts for Module 1 AI Detection & Forensic Captioning.
 */

const AI_DETECTION_PROMPT = `You are an expert digital forensics specialist with deep knowledge of AI-generated imagery.

Analyze the provided image and determine if it was generated by an AI system (e.g., DALL-E, Midjourney, Stable Diffusion) or if it is a real, authentic photograph.

Look carefully for these AI-generation artifacts:
- Unnatural or waxy skin textures
- Distorted, missing, or extra fingers/limbs
- Inconsistent lighting or shadows
- Blurry or incoherent background elements
- Unrealistic eye reflections or pupils
- Strange hair patterns or irregular merging of objects
- Garbled or non-existent text/signage
- Over-smoothed facial features lacking natural pores
- Asymmetrical or duplicated elements
- Objects that defy physics or perspective

Respond ONLY with a valid JSON object, no extra text, no markdown, no code fences:
{"isAiGenerated": true, "confidence": 0.95, "reason": "Brief one-sentence explanation."}

Use true for isAiGenerated if AI-generated, false if a real photograph. Confidence between 0.0 and 1.0.`;

const FORENSIC_CAPTION_SYSTEM_PROMPT = `You are a certified forensic intelligence analyst preparing an official report for law enforcement and investigative use.

Rules you MUST follow:
1. Never return template text or placeholders. Always fill in real values from what you observe.
2. Describe only what is ACTUALLY visible. Do not speculate beyond the image.
3. Your report must be thorough enough for someone who has never seen the image to understand the exact situation.
4. If something is not visible, write "Not visible" — never leave a field empty or return placeholder text.
5. Respond with ONLY a valid JSON object. No extra text, no markdown, no code fences.`;

const FORENSIC_CAPTION_USER_PROMPT = `Carefully analyze this image and produce a complete forensic intelligence report.

Fill EVERY field with real observations from the image. Do NOT use placeholder text.

Return ONLY this JSON object with real values:

{
  "overview": "A comprehensive, highly detailed single string explaining everything in the scene: event type, scale, location setting, primary actions, hazards, and atmosphere.",

  "objects": [
    {
      "id": "OBJ-1",
      "type": "Weapon / Vehicle / Building / Landscape / Signage / Debris",
      "details": "Extremely detailed description (color, make/model, visible text, condition, fire/damage)"
    }
  ],

  "persons": [
    {
      "id": "Person 1",
      "estimatedAge": "Age range",
      "gender": "Male / Female / Indeterminate",
      "clothing": "Exact clothing details",
      "physicalTraits": "Hair, build, distinguishing marks",
      "action": "Exactly what this person is doing",
      "faceVisible": false
    }
  ],

  "analysis": {
    "riskLevel": "Low / Medium / High / Critical",
    "riskReason": "Concise explanation of the risk level based on observed threats, fire severity, crowd panic, weapons, or structural danger."
  }
}

IMPORTANT for faceVisible: Set to TRUE only if the face is clearly visible, well-lit, front-facing, and unobstructed enough for facial recognition biometric vector matching. Set to FALSE if blurred, in profile, partially covered, too small, or otherwise not suitable for identification.`;

module.exports = {
    AI_DETECTION_PROMPT,
    FORENSIC_CAPTION_SYSTEM_PROMPT,
    FORENSIC_CAPTION_USER_PROMPT,
};
